"""日本語・英語のUI辞書。データの内部コードは言語に依存しない。"""
LABELS = {
'dashboard': ('ダッシュボード','Overview'), 'customers': ('顧客一覧','Clients'), 'followup': ('フォローアップ','Follow-ups'), 'history': ('対応履歴','Activity'), 'team': ('スタッフ','Team'), 'settings': ('設定・連携','Settings'),
'win': ('ウィン','Win'), 'ginza': ('銀座店','Ginza'), 'osaka': ('大阪店（デモ）','Osaka · Demo'), 'workspace': ('ワークスペース','Workspace'), 'language': ('表示言語','Language'), 'my_clients': ('担当のお客様','Your clients'), 'all_staff': ('スタッフ全員','All advisors'), 'advisor': ('担当スタッフ','Advisor'),
'hero': ('一人ひとりに、特別なつながりを。','Every client. A personal connection.'), 'greeting': ('ウィンさん、今日も心に残る接客を。','A thoughtful day of clienteling, Win.'), 'hero_sub': ('会話を覚えて、好みに寄り添い、次のご来店へ。','Remember the conversation. Make the next visit personal.'),
'customers_sub': ('好みも、会話も、大切なひとつのノートに。','Their preferences, their conversations, all in one place.'), 'followup_sub': ('小さな気配りを、忘れずに。','A little follow-up goes a long way.'), 'history_sub': ('次の接客につながる、これまでの会話。','Every conversation brings you closer.'), 'team_sub': ('お客様との関係を育むチーム。','The people behind every personal connection.'), 'settings_sub': ('あなたらしい接客のために。','A workspace that feels like you.'),
'new_client': ('顧客を登録','Add client'), 'attention': ('連絡が必要','Needs attention'), 'reply_count': ('返信が必要','Awaiting your reply'), 'done_count': ('本日の対応済み','Completed today'), 'people': ('名','clients'), 'total_hint': ('一人ひとりを、もっと深く知る。','Know every client a little better.'), 'attention_hint': ('次のご連絡を、忘れずに。','Make time for your next follow-up.'), 'reply_hint': ('お客様へのお返事を。','A conversation is waiting for you.'), 'done_hint': ('今日の丁寧なコミュニケーション。','Thoughtful conversations, made today.'),
'focus': ('今日のひと声','Today’s personal touch'), 'focus_sub': ('優先してご連絡したいお客様','The conversations to start with'), 'view_all': ('すべて見る','View all'), 'all': ('すべて','All clients'), 'completed': ('対応済み','Completed'), 'search': ('お名前・商品・連絡内容で検索','Search clients, interests, or conversations'), 'all_stages': ('全ステータス','All stages'), 'sort': ('並び順','Sort by'), 'priority': ('優先度順','Priority'), 'name_sort': ('名前順','Name'), 'date_sort': ('予定日順','Next follow-up'), 'list_view': ('リスト表示','List view'), 'board_view': ('ボード表示','Board view'),
'client': ('お客様','Client'), 'stage': ('商談ステータス','Stage'), 'latest': ('直近のご連絡','Last conversation'), 'next_date': ('次回フォロー','Next follow-up'), 'action': ('アクション','Action'), 'today': ('今日','Today'), 'details': ('詳細を見る','View details'), 'empty': ('該当するお客様はいません','No clients found'), 'empty_hint': ('条件を変更するか、新しいお客様を登録してください。','Try different filters or add a new client.'), 'clear': ('絞り込みを解除','Clear filters'), 'shown': ('表示中','shown'), 'client_note': ('顧客ノート','Client notebook'), 'profile': ('プロフィール','Profile'), 'record': ('対応を記録','Log a conversation'), 'conversation': ('対応履歴・フォロー','Conversations & follow-up'),
'name': ('お名前','Name'), 'kana': ('フリガナ・読み方','Pronunciation'), 'email': ('メール','Email'), 'phone': ('電話番号','Phone'), 'birthday': ('誕生日','Birthday'), 'size': ('サイズ','Size preferences'), 'interests': ('興味のある商品','Interests'), 'purchase': ('購入履歴','Purchase notes'), 'note': ('接客メモ','Personal notes'), 'type': ('対応の種類','Activity type'), 'date': ('対応日','Activity date'), 'message': ('連絡内容','Conversation notes'), 'save': ('保存する','Save changes'), 'save_activity': ('対応を保存','Save activity'), 'cancel': ('キャンセル','Cancel'), 'close': ('閉じる','Close'), 'required': ('必須','Required'), 'saved': ('保存しました','Changes saved'), 'created': ('お客様を登録しました','Client added'),
'message_hint': ('お話ししたこと、次にご案内したいこと…','What did you discuss? What would make the next visit special?'), 'activity_hint': ('受信は返信待ちに。送信・接客を記録すると未返信が解消されます。','Received messages need a reply. Sent messages and visits clear the pending reply.'), 'demo_input': ('架空のお客様の情報でお試しください。','Explore with fictional client information.'), 'no_activity': ('まだ対応履歴はありません','No conversations yet'),
'visit': ('来店','First visit'), 'proposal': ('商品提案','Proposal'), 'considering': ('検討中','Considering'), 'return': ('再来店','Return visit'), 'purchased': ('購入','Purchased'), 'aftercare': ('購入後フォロー','Aftercare'),
'sent': ('送信','Sent'), 'received': ('受信','Received'), 'meeting': ('接客','In-store visit'), 'memo': ('メモ','Note'),
'reply': ('返信が必要','Reply needed'), 'overdue': ('連絡期限超過','Overdue'), 'due': ('連絡推奨','Follow up soon'), 'done': ('対応済み','Completed'), 'normal': ('フォロー予定','Scheduled'),
'line': ('LINE連携','LINE connection'), 'line_pitch': ('会話の続きを、もっとスムーズに。','Keep the conversation flowing.'), 'line_desc': ('LINEと顧客ノートをつなぐ体験のプレビューです。','A preview of connecting LINE with your client notebook.'), 'line_notice': ('この画面はデモです。実際の接続・認証・送受信は行いません。','This is a UI preview. No connection, authentication, or messages are sent.'), 'disconnected': ('未接続','Not connected'), 'line_button': ('連携プレビューを見る','Preview connection'), 'line_feature1': ('顧客とLINEアカウントの紐づけ','Link a client’s LINE account'), 'line_feature2': ('会話の履歴をまとめて確認','See conversations in one place'), 'line_feature3': ('次のフォローに向けた下書き','Prepare a thoughtful follow-up'), 'understood': ('確認しました','Got it'),
'rules': ('連絡推奨のルール','Follow-up rules'), 'rule_red': ('未返信の受信、または予定日を過ぎたお客様','An unanswered message or a missed follow-up date'), 'rule_amber': ('今日・明日の予定、または14日以上未連絡','Due today or tomorrow, or no contact for 14 days'), 'rule_green': ('本日対応し、上の条件に当てはまらないお客様','Contacted today, with no outstanding follow-up'), 'rule_gray': ('それ以外のフォロー予定','Other scheduled follow-ups'), 'no_notifications': ('色とラベルのみでお知らせします。外部通知はありません。','Shown with color and labels. No external notifications.'),
'about': ('このポートフォリオについて','About this portfolio'), 'about_text': ('MAISONは自主制作のコンセプトです。Louis Vuittonの公式サービスではありません。','MAISON is an independent portfolio concept, not an official Louis Vuitton service.'), 'storage_text': ('架空データの変更は、このブラウザに保存されます。判定・集計・入力検証・画面生成はPythonで処理します。','Changes to fictional data stay in this browser. Python handles validation, follow-up rules, summaries, and page rendering.'), 'store_notice': ('店舗切り替えはデモ表示です。店舗間のアクセス制御はありません。','Store switching is a visual demo, not tenant access control.'), 'reset': ('デモデータをリセット','Reset demo data'), 'reset_confirm': ('このブラウザで編集した内容を初期データに戻します。','Replace changes in this browser with the original demo data.'), 'reset_done': ('デモデータをリセットしました','Demo data reset'), 'demo': ('架空データのポートフォリオ','Fictional portfolio data'), 'you': ('あなた','You'), 'loading': ('顧客ノートを開いています…','Opening your client notebook…'),
'error': ('処理できませんでした。入力内容や接続を確認して、もう一度お試しください。','Something went wrong. Check your input and connection, then try again.'), 'storage_error': ('ブラウザに保存できません。変更は再読み込みで失われます。','Browser storage is unavailable. Changes will be lost on reload.'), 'invalid': ('入力内容を確認してください。氏名・日付・連絡内容が必要です。','Please check the required name, dates, and conversation details.'), 'quote': ('「覚えていてくれた。」その喜びが、次のご来店につながる。','“You remembered.” Two words that turn a visit into a relationship.'), 'welcome_record': ('初回のご来店。顧客ノートを作成しました。','First visit. A new client notebook was created.'), 'retry': ('再試行','Try again'), 'more': ('その他','More'),
}
LANGUAGES = ('ja', 'en')

def language(value):
    return value if value in LANGUAGES else 'ja'

def translator(lang):
    index = 1 if lang == 'en' else 0
    return lambda key: LABELS[key][index] if key in LABELS else key

def localized(value, lang):
    if isinstance(value, dict):
        return str(value.get(lang, value.get('ja', '')))
    return str(value or '')
